/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Classes.Piece;

/**
 *
 * @author Wejda
 */
public class Cart extends javax.swing.JFrame {


   OrderDetails order = new OrderDetails();
    /**
     * Creates new form Cart
     */
    public Cart() {
        initComponents();
        if (ChooseService.ServiceType != null) {
            if (ChooseService.ServiceType.equalsIgnoreCase("cleaning")) {
                TypeOfService.setText("cleaning");
                int pricePerPc = (int) order.pricePerPc;
                NumberOfPieces.setText(pricePerPc + " Piece");
                total.setText((pricePerPc * 30) + " SR");

            } else if (ChooseService.ServiceType.equalsIgnoreCase("ironing")) {
                TypeOfService.setText("ironing");
                int pricePerPc = (int) order.pricePerPc;
                total.setText((pricePerPc * 20) + " SR");
                NumberOfPieces.setText(pricePerPc + " Piece");
            } else if (ChooseService.ServiceType.equalsIgnoreCase("both")) {
                TypeOfService.setText("both");
                int pricePerPc = (int) order.pricePerPc;
                NumberOfPieces.setText(pricePerPc + " Piece");
                total.setText((pricePerPc * 50) + " SR");
            }
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cancelOrder = new javax.swing.JButton();
        ConfirmOrder = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TypeOfService = new javax.swing.JLabel();
        NumberOfPieces = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(404, 896));
        setMinimumSize(new java.awt.Dimension(404, 896));
        setPreferredSize(new java.awt.Dimension(404, 896));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 35, 95, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 100, 139));
        jLabel2.setText("Type of services : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 100, 139));
        jLabel3.setText("Number of pieces : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 100, 139));
        jLabel4.setText("Total ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 459, -1, -1));

        cancelOrder.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        cancelOrder.setForeground(new java.awt.Color(102, 100, 139));
        cancelOrder.setText("Cancel order");
        getContentPane().add(cancelOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 610, -1, -1));

        ConfirmOrder.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        ConfirmOrder.setForeground(new java.awt.Color(102, 100, 139));
        ConfirmOrder.setText("Confirm order");
        ConfirmOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmOrderActionPerformed(evt);
            }
        });
        getContentPane().add(ConfirmOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 660, -1, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 114, -1, -1));

        TypeOfService.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        getContentPane().add(TypeOfService, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 80, 20));

        NumberOfPieces.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        getContentPane().add(NumberOfPieces, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 80, 20));

        total.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 459, 150, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Cart.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmOrderActionPerformed
        // TODO add your handling code here:
          CheckoutFrame check = new CheckoutFrame();
            check.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_ConfirmOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmOrder;
    private javax.swing.JLabel NumberOfPieces;
    private javax.swing.JLabel TypeOfService;
    private javax.swing.JButton cancelOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
