/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Wejda
 */
public class SignUp extends javax.swing.JFrame {

        boolean validInfo;

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

     private boolean checkName() {
      boolean valid = true;
        String Name = CustomerName.getText().trim();
        name_error.setText(" ");

        if (Name.matches("[a-zA-Z_]+")) {
            valid = true;
            name_error.setText(" ");

        } else if (Name.matches("[0-9]+")) {

            valid = false;
            name_error.setText("Invalid Name!");
            name_error.setForeground(Color.red);

        } else {
            valid = false;
        //   JOptionPane.showMessageDialog(null, "Please Enter Your Name", "Error", JOptionPane.ERROR_MESSAGE); 
            name_error.setText("Please Enter Your Name");
            name_error.setForeground(Color.red);

        }
        return valid;
    
    }
     
     
       private boolean checkEmail() {
        boolean valid = true;
        String Email = email.getText().trim();
        email_error.setText("");

      if (Email.equals("")) {
            valid = false;
            email_error.setText("Please Enter Your Email");
            email_error.setForeground(Color.red);

        } else if (Email.matches("^\\w+@[a-zA-Z_]+?\\.[a-zA-Z]{2,3}$")) {
            valid = true;
            email_error.setText("");

        } else {
            valid = false;
            email_error.setText("Invalid Email");
            email_error.setForeground(Color.red);

        }
        return valid;
    }
       private boolean checkPhone() {
        boolean valid = true;
        String Phone_num = phone.getText();
        PhoneNumber_error.setText(" ");

        if (Phone_num.trim().equals("")) {
            valid = false;
            PhoneNumber_error.setText("Please Enter Your Phone");
            PhoneNumber_error.setForeground(Color.red);

        } else if (Phone_num.matches("[0-9]+") && Phone_num.length() == 10) {
            valid = true;
            PhoneNumber_error.setText(" ");

        } else {
            valid = false;
            PhoneNumber_error.setText("Enter a 10-digit phone number");
            PhoneNumber_error.setForeground(Color.red);

        }
        return valid;
    }
       private boolean checkPassword() {

        boolean valid = true;
        String PasswordNum = PasswordNumber.getText();
        Password_error.setText("");

        if (PasswordNum.trim().equals("")) {
            valid = false;
            Password_error.setText("Please Enter Password");
            Password_error.setForeground(Color.red);

        } else if (PasswordNum.matches("^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?!.*\\s).{6,10}$")) {
              valid = true;
              Password_error.setText("");
        } else {

            valid = false;
            Password_error.setText("Incorrect Password");
            Password_error.setForeground(Color.red);

        }

        return valid;
    }
         private boolean ConfirmPassword() {

        boolean valid = true;
        String PasswordNum = ConfirmPassword.getText();
        confirm_error.setText("");

        if (PasswordNum.trim().equals("")) {
            valid = false;
            confirm_error.setText("Please confirm Password");
            confirm_error.setForeground(Color.red);

        } else if (PasswordNum.equals(PasswordNum)) {
              valid = true;
        } else {

            valid = false;
            confirm_error.setText("Incorrect Password");
            confirm_error.setForeground(Color.red);

            confirm_error.setText("");
        }

        return valid;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        CustomerName = new javax.swing.JTextField();
        name_error = new javax.swing.JLabel();
        EmailAddress = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        email_error = new javax.swing.JLabel();
        PhoneNumber = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        PhoneNumber_error = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        PasswordNumber = new javax.swing.JTextField();
        Password_error = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ConfirmPassword = new javax.swing.JTextField();
        confirm_error = new javax.swing.JLabel();
        go_to_chooseService = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 896));
        setMinimumSize(new java.awt.Dimension(400, 896));
        setPreferredSize(new java.awt.Dimension(400, 896));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 360, 60, 20));

        name.setText("Name");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        CustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerNameActionPerformed(evt);
            }
        });
        getContentPane().add(CustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 300, -1));
        getContentPane().add(name_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 170, 10));

        EmailAddress.setText("Email address");
        getContentPane().add(EmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 300, -1));
        getContentPane().add(email_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, -1, -1));

        PhoneNumber.setText("Phone Number");
        getContentPane().add(PhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, -1, -1));
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 300, -1));
        getContentPane().add(PhoneNumber_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, -1, -1));

        password.setText("Password");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, -1, -1));
        getContentPane().add(PasswordNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, 300, -1));
        getContentPane().add(Password_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 720, -1, -1));

        jLabel8.setText("Confirm Password");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 740, -1, -1));
        getContentPane().add(ConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 760, 300, -1));
        getContentPane().add(confirm_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 790, -1, -1));

        go_to_chooseService.setText("Create Account");
        go_to_chooseService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go_to_chooseServiceActionPerformed(evt);
            }
        });
        getContentPane().add(go_to_chooseService, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 810, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/signup (1)-1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, -1, 968));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerNameActionPerformed
        // TODO add your handling code here:
          CustomerName.setText(" ");
          CustomerName.setForeground(Color.BLACK);
    }//GEN-LAST:event_CustomerNameActionPerformed

    private void go_to_chooseServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go_to_chooseServiceActionPerformed
        // TODO add your handling code here:
        boolean validName = checkName();
        boolean validEmail = checkEmail();
        boolean validPhone = checkPhone();
        boolean validPassword = checkPassword();
        boolean validConfirm=ConfirmPassword();

        validInfo = validPassword && validEmail && validPhone && validName&&validConfirm;

        if (validInfo == true) {
            ChooseService choose = new ChooseService();
            choose.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_go_to_chooseServiceActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
         this.dispose();
        new LoginPage().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ConfirmPassword;
    private javax.swing.JTextField CustomerName;
    private javax.swing.JLabel EmailAddress;
    private javax.swing.JTextField PasswordNumber;
    private javax.swing.JLabel Password_error;
    private javax.swing.JLabel PhoneNumber;
    private javax.swing.JLabel PhoneNumber_error;
    private javax.swing.JLabel confirm_error;
    private javax.swing.JTextField email;
    private javax.swing.JLabel email_error;
    private javax.swing.JButton go_to_chooseService;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name_error;
    private javax.swing.JLabel password;
    private javax.swing.JTextField phone;
    // End of variables declaration//GEN-END:variables
}
